use crate::{
    core::IrisContext,
    models::Palette,
    modules::ConfigGenerator,
    utils::{self, Status},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::Path};

/// Config generator for btop utility
pub struct BtopGenerator;

impl ConfigGenerator for BtopGenerator {
    fn name(&self) -> &str {
        "btop"
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let theme_name = &ctx.state.current_theme;
        let display_name = utils::capitalize(theme_name);
        let task = Status::step(&format!("Configuring {}...", self.name().cyan()), 2);

        let btop_dir = dirs::home_dir()
            .context("Cannot get the home directory!")?
            .join(".config/btop");
        let themes_dir = btop_dir.join("themes");

        if !themes_dir.exists() {
            task.info("Creating btop themes directory...");
            fs::create_dir_all(&themes_dir)?;
        }

        let cache_file = ctx
            .paths
            .cache
            .join(format!("btop_themes/{}.theme", theme_name));
        let btop_theme_link = themes_dir.join(format!("{}.theme", theme_name));

        fs::create_dir_all(cache_file.parent().unwrap())?;
        let content = self.build_config(p, &display_name);

        fs::write(&cache_file, content)
            .with_context(|| format!("Failed to write btop theme to {:?}", cache_file))?;

        task.info(&format!(
            "Theme {} generated in cache.",
            display_name.yellow()
        ));

        if !themes_dir.exists() {
            fs::create_dir_all(&themes_dir)?;
        }
        if btop_theme_link.exists() || btop_theme_link.is_symlink() {
            fs::remove_file(&btop_theme_link)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            task.info(&format!(
                "Creating link in btop/themes/ for {}",
                display_name.yellow()
            ));
            symlink(&cache_file, &btop_theme_link).with_context(|| {
                format!(
                    "Failed to create symlink {:?} -> {:?}",
                    btop_theme_link, cache_file
                )
            })?;
        }

        let conf_path = btop_dir.join("btop.conf");
        if conf_path.exists() {
            task.info(&format!(
                "Setting color_theme = \"{}\" in btop.conf",
                theme_name.bold()
            ));
            self.update_btop_conf(&conf_path, theme_name)?;
        } else {
            Status::warn("btop.conf not found. Theme generated but not activated.", 3);
        }

        task.done(Some(&format!("{} is ready to sync!", self.name().cyan())));
        Ok(())
    }
}

impl BtopGenerator {
    /// Build btop theme content using the provided palette
    fn build_config(&self, p: &Palette, name: &str) -> String {
        format!(
            r#"# Theme: {name}, generated by Iris
# Main background and foreground
theme[main_bg]="{bg}"
theme[main_fg]="{fg}"

# Title and borders
theme[title]="{fg}"
theme[hi_fg]="{keyword}"
theme[selected_bg]="{sel}"
theme[selected_fg]="{white}"
theme[inactive_fg]="{comment}"

# CPU colors
theme[cpu_box]="{green}"
theme[cpu_text]="{fg}"
theme[cpu_start]="{green}"
theme[cpu_mid]="{yellow}"
theme[cpu_end]="{orange}"

# Memory colors
theme[mem_box]="{type_name}"
theme[mem_text]="{fg}"
theme[mem_start]="{type_name}"
theme[mem_mid]="{func}"
theme[mem_end]="{tag}"

# Network colors
theme[net_box]="{string}"
theme[net_text]="{fg}"
theme[net_start]="{string}"
theme[net_mid]="{constant}"
theme[net_end]="{attribute}"

# Process colors
theme[proc_box]="{keyword}"
theme[proc_text]="{fg}"
theme[proc_start]="{green}"
theme[proc_mid]="{keyword}"
theme[proc_end]="{orange}"

# Graph colors
theme[graph_text]="{comment}"
theme[meter_bg]="{line_hl}"
theme[process_start]="{green}"
theme[process_mid]="{keyword}"
theme[process_end]="{orange}"

# Temperature colors
theme[temp_start]="{green}"
theme[temp_mid]="{yellow}"
theme[temp_end]="{orange}"

# Additional UI elements
theme[div_line]="{line_hl}"
theme[temp_crit]="{orange}"
theme[temp_high]="{yellow}"
theme[temp_low]="{green}"
        "#,
            bg = p.bg,
            fg = p.fg,
            keyword = p.keyword,
            sel = p.sel,
            white = p.white,
            comment = p.comment,
            line_hl = p.line_hl,
            type_name = p.type_name,
            func = p.func,
            tag = p.tag,
            string = p.string,
            constant = p.constant,
            attribute = p.attribute,
            green = p.ansi[2],
            yellow = p.ansi[3],
            orange = p.ansi[9],
        )
    }

    /// Update color_theme setting in btop.conf
    fn update_btop_conf(&self, path: &Path, name: &str) -> Result<()> {
        if !path.exists() {
            return Ok(());
        }

        let content = fs::read_to_string(path)?;
        let mut lines: Vec<String> = content.lines().map(|s| s.to_string()).collect();
        let mut updated = false;

        let theme_line = format!("color_theme = \"{}\"", name);

        for line in lines.iter_mut() {
            if line.trim_start().starts_with("color_theme =") {
                *line = theme_line.clone();
                updated = true;
                break;
            }
        }

        if !updated {
            lines.push(theme_line);
        }

        fs::write(path, lines.join("\n"))?;
        Ok(())
    }
}
