use crate::{context::AppContext, models::Palette};
use anyhow::{Context, Result};

/// Apply generated fzf color arguments to .zshrc
pub fn apply(palette: &Palette, ctx: &AppContext) -> Result<()> {
    let cache_file = ctx.cache_path.join("fzf.sh");
    let fzf_colors: String = crate::generators::fzf::build_fzf_args(palette);

    let content: String = format!(
        r#"# Theme: {theme}, generated by Iris
export FZF_DEFAULT_OPTS="--color='{colors}' --layout=reverse --height=40% --border""#,
        theme = ctx.state.current_theme,
        colors = fzf_colors
    );

    std::fs::write(&cache_file, content)
        .with_context(|| format!("Failed to write FZF config to {:?}", cache_file))?;
    Ok(())
}
