use crate::{core::IrisContext, models::Palette, modules::ConfigGenerator, utils::Status};
use anyhow::{Context, Result};
use colored::Colorize;

/// Config generator for fzf utility
pub struct FzfGenerator;

impl ConfigGenerator for FzfGenerator {
    fn name(&self) -> &str {
        "fzf"
    }

    fn is_installed(&self) -> bool {
        let home = dirs::home_dir().unwrap_or_default();
        which::which("fzf").is_ok() || home.join(".zshrc").exists()
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let task = Status::step(&format!("Configuring {}...", self.name().cyan()), 2);

        let cache_file = ctx.paths.cache.join("fzf.sh");
        let fzf_colors: String = self.build_config(p);

        let content: String = format!(
            r#"# Theme: {theme}, generated by Iris
    export FZF_DEFAULT_OPTS="--color='{colors}' --layout=reverse --height=40% --border""#,
            theme = ctx.state.current_theme,
            colors = fzf_colors
        );

        task.info(&format!("Generating script in: {}", cache_file.display()));

        std::fs::write(&cache_file, content)
            .with_context(|| format!("Failed to write FZF config to {:?}", cache_file))?;

        #[cfg(unix)]
        task.info("Fzf colors exported to shell script.");

        task.done(Some("Fzf is ready to source."));
        Ok(())
    }
}

impl FzfGenerator {
    /// Build color arguments for fzf
    pub fn build_config(&self, p: &Palette) -> String {
        let c = |hex: &str| hex.trim_start_matches('#').to_string();

        let fg = c(&p.fg);
        let accent = c(&p.ansi[3]);
        let match_c = c(&p.ansi[5]);
        let dimmed = c(&p.ansi[8]);

        format!(
            "bg:-1,fg:#{fg},\
            bg+:-1,fg+:#{accent}:bold,\
            hl:#{match_c},hl+:#{match_c}:underline,\
            pointer:#{accent},info:#{dimmed},border:#{dimmed},\
            prompt:#{accent},marker:#{accent},spinner:#{match_c}",
            fg = fg,
            accent = accent,
            match_c = match_c,
            dimmed = dimmed
        )
    }
}
