use crate::{
    core::IrisContext,
    models::Palette,
    modules::ConfigGenerator,
    utils::{self, Status},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for ghostty terminal
pub struct GhosttyGenerator;

impl ConfigGenerator for GhosttyGenerator {
    fn name(&self) -> &str {
        "ghostty"
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let task = Status::step(&format!("Configuring {}...", self.name().cyan()), 2);

        let ghostty_dir: PathBuf = dirs::home_dir()
            .context("Cannot get the home directory!")?
            .join(".config/ghostty");
        let cache_file: PathBuf = ctx.paths.cache.join("ghostty.conf");
        let link_path: PathBuf = ghostty_dir.join("current_theme.conf");

        let config_content: String =
            self.build_config(p, &utils::capitalize(&ctx.state.current_theme));

        fs::create_dir_all(&ctx.paths.cache).context("Failed to create cache directory")?;
        fs::write(&cache_file, config_content)
            .with_context(|| format!("Failed to write ghostty cache to {:?}", cache_file))?;

        task.info(&format!(
            "Theme {} generated in cache.",
            utils::capitalize(&ctx.state.current_theme).yellow()
        ));

        if !ghostty_dir.exists() {
            Status::warn("Ghostty config directory not found. Creating it...", 3);
            std::fs::create_dir_all(&ghostty_dir).ok();
        }

        if link_path.exists() || link_path.is_symlink() {
            std::fs::remove_file(&link_path).ok();
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            task.info("Linking cache to Ghostty config...");
            symlink(&cache_file, &link_path).with_context(|| {
                format!(
                    "Failed to create symlink {:?} -> {:?}",
                    link_path, cache_file
                )
            })?;
        }

        task.done(Some(&format!("{} sync complete.", self.name().cyan())));
        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let ghostty_config: PathBuf = dirs::home_dir()?.join(".config/ghostty/config");

        if ghostty_config.exists() {
            let content = fs::read_to_string(&ghostty_config).unwrap_or_default();
            if content.contains("current_theme.conf") {
                return None;
            }

            return Some(format!(
                "Theme won't load until you add to {}:\n     {}",
                "~/.config/ghostty/config".cyan(),
                "config-file = ~/.config/ghostty/current_theme.conf".yellow()
            ));
        }

        Some(format!(
            "No {} found. Create it and add:\n     {}",
            "~/.config/ghostty/config".cyan(),
            "config-file = ~/.config/ghostty/current_theme.conf".yellow()
        ))
    }
}

impl GhosttyGenerator {
    /// Build config theme for ghostty
    pub fn build_config(&self, p: &Palette, name: &str) -> String {
        let mut cfg = String::new();
        cfg.push_str(&format!("# Theme: {}, generated by Iris\n\n", name));

        cfg.push_str(&format!("background = {}\n", p.bg));
        cfg.push_str(&format!("foreground = {}\n", p.fg));
        cfg.push_str(&format!("cursor-color = {}\n", p.white));
        cfg.push_str(&format!("selection-background = {}\n", p.sel));
        cfg.push_str(&format!("selection-foreground = {}\n\n", p.bg));

        for (idx, color) in p.ansi.iter().enumerate() {
            cfg.push_str(&format!("palette = {}={}\n", idx, color));
        }

        cfg
    }
}
