use crate::{core::IrisContext, models::Palette, modules::ConfigGenerator};
use anyhow::{Context, Result};
#[cfg(unix)]
use std::os::unix::fs::symlink;

/// Config generator for ghostty terminal
pub struct GhosttyGenerator;

impl ConfigGenerator for GhosttyGenerator {
    fn name(&self) -> &str {
        "ghostty"
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let ghostty_dir = ctx.paths.config.join("ghostty");
        let cache_file = ctx.paths.cache.join("ghostty.conf");
        let link_path = ghostty_dir.join("current_theme.conf");

        let config_content: String = self.build_config(p, &ctx.state.current_theme);

        std::fs::create_dir_all(&ctx.paths.cache).context("Failed to create cache directory")?;
        std::fs::write(&cache_file, config_content)
            .with_context(|| format!("Failed to write ghostty cache to {:?}", cache_file))?;

        if !ghostty_dir.exists() {
            std::fs::create_dir_all(&ghostty_dir).ok();
        }

        if link_path.exists() || link_path.is_symlink() {
            std::fs::remove_file(&link_path).ok();
        }

        #[cfg(unix)]
        symlink(&cache_file, &link_path).with_context(|| {
            format!(
                "Failed to create symlink {:?} -> {:?}",
                link_path, cache_file
            )
        })?;

        Ok(())
    }
}

impl GhosttyGenerator {
    /// Build config theme for ghostty
    pub fn build_config(&self, p: &Palette, name: &str) -> String {
        let mut cfg = String::new();
        cfg.push_str(&format!("# Theme: {}, generated by Iris\n\n", name));

        cfg.push_str(&format!("background = {}\n", p.bg));
        cfg.push_str(&format!("foreground = {}\n", p.fg));
        cfg.push_str(&format!("cursor-color = {}\n", p.white));
        cfg.push_str(&format!("selection-background = {}\n", p.sel));
        cfg.push_str(&format!("selection-foreground = {}\n\n", p.bg));

        for (idx, color) in p.ansi.iter().enumerate() {
            cfg.push_str(&format!("palette = {}={}\n", idx, color));
        }

        cfg
    }
}
