use crate::{
    core::IrisContext,
    models::Palette,
    modules::ConfigGenerator,
    utils::{self, Status},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;

/// Config generator for yazi
pub struct YaziGenerator;

impl ConfigGenerator for YaziGenerator {
    fn name(&self) -> &str {
        "yazi"
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let theme_name = &ctx.state.current_theme;
        let task = Status::step(&format!("Configuring {}...", self.name().cyan()), 2);

        let yazi_dir = dirs::home_dir()
            .context("Cannot get the home directory!")?
            .join(".config/yazi");
        let cache_file = ctx
            .paths
            .cache
            .join(format!("yazi_themes/{}.toml", theme_name));
        let theme_link = yazi_dir.join("theme.toml");

        let content = self.build_config(p, theme_name);

        fs::create_dir_all(cache_file.parent().unwrap())?;
        fs::write(&cache_file, content)?;
        task.info(&format!(
            "Theme {} generated in cache.",
            utils::capitalize(&ctx.state.current_theme).yellow()
        ));

        if !yazi_dir.exists() {
            fs::create_dir_all(&yazi_dir)?;
        }
        if theme_link.exists() || theme_link.is_symlink() {
            fs::remove_file(&theme_link)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            task.info("Linking theme.toml to Yazi config...");
            symlink(&cache_file, &theme_link).with_context(|| {
                format!(
                    "Failed to create symlink {:?} -> {:?}",
                    theme_link, cache_file
                )
            })?;
        }

        task.done(Some(&format!("Theme applied to {}.", self.name().cyan())));
        Ok(())
    }
}

impl YaziGenerator {
    /// Build yazi theme
    fn build_config(&self, p: &Palette, name: &str) -> String {
        let bat_theme_path = dirs::home_dir()
            .map(|h| format!("{}/.config/bat/themes/{}.tmTheme", h.display(), name))
            .unwrap_or_default();

        let red = &p.ansi[1];
        let green = &p.ansi[2];
        let orange = &p.ansi[3];
        let blue = &p.ansi[4];
        let magenta = &p.ansi[5];
        let teal = &p.ansi[6];
        let tan = &p.ansi[7];

        let br_red = &p.ansi[9];
        let br_green = &p.ansi[10];
        let br_orange = &p.ansi[11];
        let br_blue = &p.ansi[12];
        let br_magenta = &p.ansi[13];
        let br_teal = &p.ansi[14];

        let line_hl = if p.line_hl == "#cccccc" {
            &p.sel
        } else {
            &p.line_hl
        };

        format!(
            r#"# Theme: {name}, generated by Iris
# vim:fileencoding=utf-8:foldmethod=marker

[manager]
cwd = {{ fg = "{br_red}", bold = true }}

hovered         = {{ fg = "{bg}", bg = "{orange}", bold = true }}
preview_hovered = {{ underline = true }}
symlink_target = {{ fg = "{gutter_fg}" }}

find_keyword  = {{ fg = "{br_orange}", bold = true }}
find_position = {{ fg = "{br_magenta}" }}

marker_selected = {{ fg = "{br_green}", bold = true }}
marker_copied   = {{ fg = "{br_orange}", bold = true }}
marker_cut      = {{ fg = "{br_red}", bold = true }}

tab_active   = {{ fg = "{bg}", bg = "{teal}", bold = true }}
tab_inactive = {{ fg = "{tan}", bg = "{line_hl}" }}
tab_width    = 1

border_symbol = "│"
border_style  = {{ fg = "{tan}" }}

syntect_theme = "{bat_theme_path}"

[status]
separator_open  = ""
separator_close = ""
separator_style = {{ fg = "{line_hl}", bg = "{line_hl}" }}

mode_normal = {{ fg = "{bg}", bg = "{br_teal}",    bold = true }}
mode_select = {{ fg = "{bg}", bg = "{br_green}",   bold = true }}
mode_unset  = {{ fg = "{bg}", bg = "{br_magenta}", bold = true }}

filename   = {{ fg = "{white}", bold = true }}
filesize   = {{ fg = "{tan}" }}
permissions = {{ fg = "{comment}" }}

progress_label  = {{ fg = "{br_orange}", bold = true }}
progress_normal = {{ fg = "{teal}" }}
progress_error  = {{ fg = "{red}" }}

permissions_t = {{ fg = "{br_teal}" }}
permissions_r = {{ fg = "{br_orange}" }}
permissions_w = {{ fg = "{red}" }}
permissions_x = {{ fg = "{br_green}" }}
permissions_s = {{ fg = "{tan}" }}

[filetype]
rules = [
  {{ name = "*/",                           fg = "{br_green}", bold = true }},

  {{ mime = "text/x-shellscript",           fg = "{green}", bold = true }},

  {{ mime = "image/*",                      fg = "{br_teal}" }},
  {{ mime = "video/*",                      fg = "{br_orange}" }},
  {{ mime = "audio/*",                      fg = "{magenta}" }},

  {{ mime = "application/zip",              fg = "{br_magenta}" }},
  {{ mime = "application/gzip",             fg = "{br_magenta}" }},
  {{ mime = "application/x-tar",            fg = "{br_magenta}" }},
  {{ mime = "application/x-7z-compressed",  fg = "{br_magenta}" }},
  {{ mime = "application/x-rar-compressed", fg = "{br_magenta}" }},
  {{ mime = "application/zstd",             fg = "{br_magenta}" }},

  {{ mime = "application/pdf",              fg = "{red}", bold = true }},
  {{ mime = "text/markdown",                fg = "{br_orange}", italic = true }},
  {{ mime = "text/html",                    fg = "{orange}" }},
  {{ mime = "application/json",             fg = "{br_green}" }},
  {{ mime = "text/csv",                     fg = "{green}" }},

  {{ mime = "text/x-python",                fg = "{br_blue}" }},
  {{ mime = "text/x-rust",                  fg = "{br_red}" }},
  {{ mime = "text/x-c",                     fg = "{blue}" }},
  {{ mime = "text/javascript",              fg = "{br_orange}" }},
  {{ mime = "text/typescript",              fg = "{blue}" }},
  {{ mime = "text/x-go",                    fg = "{teal}" }},

  {{ name = "*.toml",                       fg = "{tan}" }},
  {{ name = "*.yaml",                       fg = "{tan}" }},
  {{ name = "*.yml",                        fg = "{tan}" }},
  {{ name = "*.env",                        fg = "{br_green}", bold = true }},
  {{ name = "*.lock",                       fg = "{gutter_fg}" }},
  {{ name = ".gitignore",                   fg = "{gutter_fg}" }},
  {{ name = "Makefile",                     fg = "{br_red}", bold = true }},
  {{ name = "Dockerfile",                   fg = "{blue}", bold = true }},
  {{ name = "README*",                      fg = "{br_orange}", bold = true }},
  {{ name = "LICENSE*",                     fg = "{tan}" }},

  {{ name = "*",                            fg = "{fg}" }},
]

[icon]
conds = [
  {{ if = "dir & hovered", text = "",  fg = "{bg}",  bg = "{orange}" }},
  {{ if = "dir",           text = "",  fg = "{br_green}" }},
  {{ if = "link & hovered",text = "",  fg = "{bg}",  bg = "{teal}" }},
  {{ if = "link",          text = "",  fg = "{teal}" }},
  {{ if = "exec",          text = "",  fg = "{br_green}" }},
  {{ if = "orphan",        text = "",  fg = "{red}" }},
  {{ if = "!dir",          text = "",  fg = "{fg}" }},
]
"#,
            name = name,
            bg = p.bg,
            fg = p.fg,
            white = p.white,
            comment = p.comment,
            tan = tan,
            line_hl = line_hl,
            gutter_fg = p.gutter_fg,
            orange = orange,
            green = green,
            red = red,
            magenta = magenta,
            teal = teal,
            blue = blue,
            br_red = br_red,
            br_green = br_green,
            br_orange = br_orange,
            br_blue = br_blue,
            br_magenta = br_magenta,
            br_teal = br_teal,
            bat_theme_path = bat_theme_path,
        )
    }
}
