use crate::{
    core::IrisContext,
    models::Palette,
    modules::{Generator, GeneratorType},
    utils::{self},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for tmux
pub struct TmuxGenerator;

impl Generator for TmuxGenerator {
    fn name(&self) -> &str {
        "tmux"
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::Multiplexer
    }

    fn target_file_name(&self, theme: &str) -> String {
        format!("{}.conf", theme)
    }

    fn resolve_config_directory(&self) -> PathBuf {
        dirs::home_dir()
            .map(|p| p.join(".config").join("tmux").join("themes"))
            .unwrap_or_else(|| PathBuf::from(".config/tmux/themes"))
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let display_name: String = utils::capitalize(&p.name);

        let themes_dir: PathBuf = self.resolve_config_directory();
        let theme_file_name: String = self.target_file_name(&p.name);

        let cache_file = ctx.paths.cache.join("tmux_themes").join(&theme_file_name);
        let theme_link: PathBuf = themes_dir.join(&theme_file_name);

        let content: String = self.build_config(p);
        if let Some(parent) = cache_file.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create cache directory for {}", self.name()))?;
        }

        fs::write(&cache_file, content)
            .with_context(|| format!("Failed to write tmux theme to {:?}", cache_file))?;

        ctx.log.info(&format!(
            "Theme {} generated in cache.",
            display_name.yellow()
        ));

        if !themes_dir.exists() {
            ctx.log
                .info(&format!("Creating {} themes directory...", "tmux".bold()));
            fs::create_dir_all(&themes_dir)?;
        }

        if theme_link.exists() || theme_link.is_symlink() {
            fs::remove_file(&theme_link)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            ctx.log.info(&format!(
                "Creating link in tmux/themes/ for {}",
                display_name.yellow()
            ));
            symlink(&cache_file, &theme_link).with_context(|| {
                format!(
                    "Failed to create symlink {:?} -> {:?}",
                    theme_link, cache_file
                )
            })?;
        }

        let tmux_root = themes_dir.parent().unwrap_or(&themes_dir);
        let conf_path: PathBuf = tmux_root.join("tmux.conf");

        if conf_path.exists() {
            ctx.log.info(&format!(
                "Patching {} to source theme {}",
                "tmux.conf".bold(),
                display_name.yellow()
            ));
            self.update_tmux_conf(&conf_path, &p.name)?;
        } else {
            ctx.log
                .warn("tmux.conf not found. Theme linked but not sourced.", 3);
        }

        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let themes_dir: PathBuf = self.resolve_config_directory();
        let tmux_conf: PathBuf = themes_dir.parent()?.join("tmux.conf");

        if !tmux_conf.exists() {
            return Some(format!(
                "No {} found at {}.\n      Create it or run tmux once, then re-apply the theme.",
                "tmux.conf".cyan(),
                tmux_conf.display().to_string().dimmed()
            ));
        }

        let content: String = fs::read_to_string(&tmux_conf).unwrap_or_default();
        let themes_dir_str: String = themes_dir.display().to_string();

        if !content.contains(&themes_dir_str) {
            return Some(format!(
                "Iris generated the theme, but you need to source it in {}:\n      {}",
                "tmux.conf".cyan(),
                "source-file ~/.config/tmux/themes/<theme>.conf".yellow()
            ));
        }

        None
    }
}

impl TmuxGenerator {
    /// Build the tmux theme conf file content
    fn build_config(&self, p: &Palette) -> String {
        let session_expr = " #S";
        let path_expr = " #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}}";

        let online = format!(
            "#{{?#{{==:#{{online_status}},on}},#[fg={func}] 󰖩 on ,#[fg={tag}] 󰖪 off }}",
            func = p.func,
            tag = p.tag,
        );
        format!(
            r##"# Theme: {name}, generated by Iris
set -g status on
set -g status-position bottom
set -g status-style bg="{bg}",fg="{fg}"
set -g status-justify absolute-centre
set -g status-left-length 100
set -g status-right-length 100

set -g status-left ""
set -ga status-left "#[bg={bg},fg={green},bold] {session_expr}  "
set -ga status-left "#[bg={bg},fg={comment},none]│"
set -ga status-left "#[bg={bg},fg={operator}]  {path_expr} "
set -ga status-left "#[bg={bg},fg={comment},none]#{{?window_zoomed_flag,│,}}"
set -ga status-left "#[bg={bg},fg={gutter_fg}]#{{?window_zoomed_flag,  zoom ,}}"

set -g status-right ""
set -g status-right "#[fg={blue},bg={bg}]#{{battery_icon}} #{{battery_percentage}} "
set -ga status-right "#[fg={comment},bg={bg}]│"
set -ga status-right "#[bg={bg}]{online}"

set -wg automatic-rename on
set -g automatic-rename-format "#{{pane_current_command}}"

set -g window-status-format " #I:#W "
set -g window-status-style bg="{bg}",fg="{gutter_fg}"
set -g window-status-last-style bg="{bg}",fg="{gutter_fg}"
set -g window-status-activity-style bg="{yellow}",fg="{bg}"
set -g window-status-bell-style bg="{keyword}",fg="{bg}",bold
set -g window-status-separator "#[fg={comment}]|"

set -g window-status-current-format " #I:#W "
set -g window-status-current-style bg="{yellow}",fg="{bg}",bold

set -g window-style bg="{bg}"
set -g window-active-style bg="{bg}"
set -g pane-border-style fg="{line_hl}"
set -g pane-active-border-style fg="{yellow}",bold

set-option -g message-style bg="{line_hl}",fg="{fg}"
set-option -g message-command-style bg="{line_hl}",fg="{fg}"
"##,
            name = utils::capitalize(&p.name),
            bg = p.bg,
            fg = p.fg,
            keyword = p.keyword,
            comment = p.comment,
            green = p.ansi[10],
            operator = p.operator,
            gutter_fg = p.gutter_fg,
            line_hl = p.line_hl,
            yellow = p.ansi[3],
            path_expr = path_expr,
            online = online,
            blue = p.ansi[12],
        )
    }

    /// Ensure tmux.conf sources the iris theme file.
    /// Replaces an existing Iris source line or appends one before the `run` line (tpm).
    fn update_tmux_conf(&self, path: &PathBuf, theme_name: &str) -> Result<()> {
        if !path.exists() {
            return Ok(());
        }

        let source_line = format!(
            "source-file \"~/.config/tmux/themes/{}.conf\" # iris-theme",
            theme_name
        );

        let content = fs::read_to_string(path)?;
        let mut lines: Vec<String> = content.lines().map(|s| s.to_string()).collect();
        let mut updated = false;

        for line in lines.iter_mut() {
            if line.contains("# iris-theme") {
                *line = source_line.clone();
                updated = true;
                break;
            }
        }

        if !updated {
            let run_pos = lines
                .iter()
                .position(|l| l.trim_start().starts_with("run ") && l.contains("tpm"));

            match run_pos {
                Some(pos) => lines.insert(pos, source_line),
                None => lines.push(source_line),
            }
        }

        fs::write(path, lines.join("\n"))?;
        Ok(())
    }
}
