use crate::{
    core::IrisContext,
    models::Palette,
    modules::{Generator, GeneratorType},
    utils::{self},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for btop utility
pub struct BtopGenerator;

impl Generator for BtopGenerator {
    fn name(&self) -> &str {
        "btop"
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::System
    }

    fn target_file_name(&self, theme: &str) -> String {
        format!("{}.theme", theme)
    }

    fn resolve_config_directory(&self) -> PathBuf {
        dirs::home_dir()
            .map(|p| p.join(".config").join("btop").join("themes"))
            .unwrap_or_else(|| PathBuf::from(".config/btop/themes"))
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let theme_name: &String = &ctx.state.current_theme;
        let display_name: String = utils::capitalize(theme_name);

        let themes_dir: PathBuf = self.resolve_config_directory();
        let theme_file_name: String = self.target_file_name(theme_name);

        let cache_file = ctx.paths.cache.join("btop_themes").join(&theme_file_name);
        let btop_theme_link: PathBuf = themes_dir.join(format!("{}.theme", theme_name));

        fs::create_dir_all(cache_file.parent().unwrap())?;
        let content: String = self.build_config(p, &display_name);
        fs::write(&cache_file, content)
            .with_context(|| format!("Failed to write btop theme to {:?}", cache_file))?;

        ctx.log.info(&format!(
            "Theme {} generated in cache.",
            display_name.yellow()
        ));

        if !themes_dir.exists() {
            ctx.log
                .info(&format!("Creating {} config directory...", "btop".bold()));
            fs::create_dir_all(&themes_dir)?;
        }

        if btop_theme_link.exists() || btop_theme_link.is_symlink() {
            fs::remove_file(&btop_theme_link)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            ctx.log.info(&format!(
                "Creating link in btop/themes/ for {}",
                display_name.yellow()
            ));
            symlink(&cache_file, &btop_theme_link).with_context(|| {
                format!(
                    "Failed to create symlink {:?} -> {:?}",
                    btop_theme_link, cache_file
                )
            })?;
        }

        let btop_root = themes_dir.parent().unwrap_or(&themes_dir);
        let conf_path: PathBuf = btop_root.join("btop.conf");

        if conf_path.exists() {
            ctx.log.info(&format!(
                "Setting color_theme = \"{}\" in btop.conf",
                theme_name.bold()
            ));
            self.update_btop_conf(&conf_path, theme_name)?;
        } else {
            ctx.log
                .warn("btop.conf not found. Theme linked but not activated.", 3);
        }

        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let themes_dir: PathBuf = self.resolve_config_directory();
        let btop_conf: PathBuf = themes_dir.parent()?.join("btop.conf");

        if !btop_conf.exists() {
            return Some(format!(
                "No {} found. Run btop once to generate it, or create it manually at {}.",
                "btop.conf".cyan(),
                btop_conf.display().to_string().dimmed()
            ));
        }

        let content: String = fs::read_to_string(&btop_conf).unwrap_or_default();
        if !content.contains("color_theme") {
            return Some(format!(
                "Iris generated the theme, but you need to enable it in {}:\n      {}",
                "btop.conf".cyan(),
                "color_theme = \"<theme_name>\"".yellow()
            ));
        }

        None
    }
}

impl BtopGenerator {
    /// Build btop theme content using the provided palette
    fn build_config(&self, p: &Palette, name: &str) -> String {
        format!(
            r#"# Theme: {name}, generated by Iris
# Main background and foreground
theme[main_bg]="{bg}"
theme[main_fg]="{fg}"

# Title and borders
theme[title]="{fg}"
theme[hi_fg]="{keyword}"
theme[selected_bg]="{sel}"
theme[selected_fg]="{white}"
theme[inactive_fg]="{comment}"

# CPU colors
theme[cpu_box]="{green}"
theme[cpu_text]="{fg}"
theme[cpu_start]="{green}"
theme[cpu_mid]="{yellow}"
theme[cpu_end]="{orange}"

# Memory colors
theme[mem_box]="{type_name}"
theme[mem_text]="{fg}"
theme[mem_start]="{type_name}"
theme[mem_mid]="{func}"
theme[mem_end]="{tag}"

# Network colors
theme[net_box]="{string}"
theme[net_text]="{fg}"
theme[net_start]="{string}"
theme[net_mid]="{constant}"
theme[net_end]="{attribute}"

# Process colors
theme[proc_box]="{keyword}"
theme[proc_text]="{fg}"
theme[proc_start]="{green}"
theme[proc_mid]="{keyword}"
theme[proc_end]="{orange}"

# Graph colors
theme[graph_text]="{comment}"
theme[meter_bg]="{line_hl}"
theme[process_start]="{green}"
theme[process_mid]="{keyword}"
theme[process_end]="{orange}"

# Temperature colors
theme[temp_start]="{green}"
theme[temp_mid]="{yellow}"
theme[temp_end]="{orange}"

# Additional UI elements
theme[div_line]="{line_hl}"
theme[temp_crit]="{orange}"
theme[temp_high]="{yellow}"
theme[temp_low]="{green}"
        "#,
            bg = p.bg,
            fg = p.fg,
            keyword = p.keyword,
            sel = p.sel,
            white = p.white,
            comment = p.comment,
            line_hl = p.line_hl,
            type_name = p.type_name,
            func = p.func,
            tag = p.tag,
            string = p.string,
            constant = p.constant,
            attribute = p.attribute,
            green = p.ansi[2],
            yellow = p.ansi[3],
            orange = p.ansi[9],
        )
    }

    /// Update color_theme setting in btop.conf
    fn update_btop_conf(&self, path: &PathBuf, name: &str) -> Result<()> {
        if !path.exists() {
            return Ok(());
        }

        let content = fs::read_to_string(path)?;
        let mut lines: Vec<String> = content.lines().map(|s| s.to_string()).collect();
        let mut updated = false;

        let theme_line = format!("color_theme = \"{}\"", name);

        for line in lines.iter_mut() {
            if line.trim_start().starts_with("color_theme =") {
                *line = theme_line.clone();
                updated = true;
                break;
            }
        }

        if !updated {
            lines.push(theme_line);
        }

        fs::write(path, lines.join("\n"))?;
        Ok(())
    }
}
