use crate::{
    core::IrisContext,
    models::Palette,
    modules::{Generator, GeneratorType},
    utils::{self},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for btop utility
pub struct BtopGenerator;

impl Generator for BtopGenerator {
    fn name(&self) -> &str {
        "btop"
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::System
    }

    fn target_file_name(&self, theme: &str) -> String {
        format!("{}.theme", theme)
    }

    fn resolve_config_directory(&self) -> PathBuf {
        dirs::home_dir()
            .map(|p| p.join(".config").join("btop").join("themes"))
            .unwrap_or_else(|| PathBuf::from(".config/btop/themes"))
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let display_name: String = utils::capitalize(&p.name);
        let themes_dir: PathBuf = self.resolve_config_directory();
        let theme_file_name: String = self.target_file_name(&p.name);

        let cache_file = ctx.paths.cache.join("btop_themes").join(&theme_file_name);
        let btop_theme_link: PathBuf = themes_dir.join(format!("{}.theme", &p.name));

        let content: String = self.build_config(p);

        if let Some(parent) = cache_file.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create cache directory for {}", self.name()))?;
        }

        fs::write(&cache_file, content)
            .with_context(|| format!("Failed to write btop theme to {:?}", cache_file))?;

        ctx.log.info(&format!(
            "Theme {} generated in cache.",
            display_name.yellow()
        ));

        if !themes_dir.exists() {
            ctx.log
                .info(&format!("Creating {} config directory...", "btop".bold()));
            fs::create_dir_all(&themes_dir)?;
        }

        if btop_theme_link.exists() || btop_theme_link.is_symlink() {
            fs::remove_file(&btop_theme_link)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            ctx.log.info(&format!(
                "Creating link in btop/themes/ for {}",
                display_name.yellow()
            ));
            symlink(&cache_file, &btop_theme_link).with_context(|| {
                format!(
                    "Failed to create symlink {:?} -> {:?}",
                    btop_theme_link, cache_file
                )
            })?;
        }

        let btop_root = themes_dir.parent().unwrap_or(&themes_dir);
        let conf_path: PathBuf = btop_root.join("btop.conf");

        if conf_path.exists() {
            ctx.log.info(&format!(
                "Setting color_theme = \"{}\" in btop.conf",
                p.name.bold()
            ));
            self.update_btop_conf(&conf_path, &p.name)?;
        } else {
            ctx.log
                .warn("btop.conf not found. Theme linked but not activated.", 3);
        }

        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let themes_dir: PathBuf = self.resolve_config_directory();
        let btop_conf: PathBuf = themes_dir.parent()?.join("btop.conf");

        if !btop_conf.exists() {
            return Some(format!(
                "No {} found. Run btop once to generate it, or create it manually at {}.",
                "btop.conf".cyan(),
                btop_conf.display().to_string().dimmed()
            ));
        }

        let content: String = fs::read_to_string(&btop_conf).unwrap_or_default();
        if !content.contains("color_theme") {
            return Some(format!(
                "Iris generated the theme, but you need to enable it in {}:\n      {}",
                "btop.conf".cyan(),
                "color_theme = \"<theme_name>\"".yellow()
            ));
        }

        None
    }
}

impl BtopGenerator {
    /// Build btop theme content using the provided palette
    fn build_config(&self, p: &Palette) -> String {
        format!(
            r#"# Theme: {name}, generated by Iris
# Main background and foreground
theme[main_bg]="{bg}"
theme[main_fg]="{fg}"

# Title and borders
theme[title]="{fg}"
theme[hi_fg]="{keyword}"
theme[selected_bg]="{sel}"
theme[selected_fg]="{white}"
theme[inactive_fg]="{comment}"

# CPU colors
theme[cpu_box]="{green}"
theme[cpu_text]="{fg}"
theme[cpu_start]="{green}"
theme[cpu_mid]="{yellow}"
theme[cpu_end]="{orange}"

# Memory colors
theme[mem_box]="{type_name}"
theme[mem_text]="{fg}"
theme[mem_start]="{type_name}"
theme[mem_mid]="{func}"
theme[mem_end]="{tag}"

# Network colors
theme[net_box]="{string}"
theme[net_text]="{fg}"
theme[net_start]="{string}"
theme[net_mid]="{constant}"
theme[net_end]="{attribute}"

# Process colors
theme[proc_box]="{keyword}"
theme[proc_text]="{fg}"
theme[proc_start]="{green}"
theme[proc_mid]="{keyword}"
theme[proc_end]="{orange}"

# Graph colors
theme[graph_text]="{comment}"
theme[meter_bg]="{line_hl}"
theme[process_start]="{green}"
theme[process_mid]="{keyword}"
theme[process_end]="{orange}"

# Temperature colors
theme[temp_start]="{green}"
theme[temp_mid]="{yellow}"
theme[temp_end]="{orange}"

# Additional UI elements
theme[div_line]="{line_hl}"
theme[temp_crit]="{orange}"
theme[temp_high]="{yellow}"
theme[temp_low]="{green}"
"#,
            name = utils::capitalize(&p.name),
            bg = p.bg,
            fg = p.fg,
            keyword = p.keyword,
            sel = p.sel,
            white = p.white,
            comment = p.comment,
            line_hl = p.line_hl,
            type_name = p.type_name,
            func = p.func,
            tag = p.tag,
            string = p.string,
            constant = p.constant,
            attribute = p.attribute,
            green = p.ansi[2],
            yellow = p.ansi[3],
            orange = p.ansi[9],
        )
    }

    /// Update color_theme setting in btop.conf
    fn update_btop_conf(&self, path: &PathBuf, name: &str) -> Result<()> {
        if !path.exists() {
            return Ok(());
        }

        let content = fs::read_to_string(path)?;
        let mut lines: Vec<String> = content.lines().map(|s| s.to_string()).collect();
        let mut updated = false;

        let theme_line = format!("color_theme = \"{}\"", name);

        for line in lines.iter_mut() {
            if line.trim_start().starts_with("color_theme =") {
                *line = theme_line.clone();
                updated = true;
                break;
            }
        }

        if !updated {
            lines.push(theme_line);
        }

        fs::write(path, lines.join("\n"))?;
        Ok(())
    }
}

/// Unit-tests for btop generator
#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::create_test_context;
    use tempdir::TempDir;

    #[test]
    fn should_return_btop_metadata() {
        let generator = BtopGenerator;
        assert_eq!(generator.name(), "btop");
        assert_eq!(generator.generator_type(), GeneratorType::System);
        assert_eq!(generator.target_file_name("iris-dark"), "iris-dark.theme");
    }

    #[test]
    fn should_build_correct_btop_config() {
        let generator = BtopGenerator;
        let p = Palette::mock();
        let config = generator.build_config(&p);

        assert!(config.contains("theme[main_bg]"));
        assert!(config.contains("theme[cpu_start]"));
        assert!(config.contains("theme[mem_mid]"));
        assert!(config.contains(&p.bg));
        assert!(config.contains(&p.ansi[2]));
    }

    #[test]
    fn should_generate_setup_hint_for_btop() {
        let generator = BtopGenerator;
        let temp_dir: TempDir = TempDir::new("btop_test").unwrap();

        temp_env::with_vars(
            vec![
                ("XDG_CONFIG_HOME", Some(temp_dir.path())),
                ("HOME", Some(temp_dir.path())),
            ],
            || {
                let btop_dir = generator
                    .resolve_config_directory()
                    .parent()
                    .unwrap()
                    .to_path_buf();
                let btop_conf = btop_dir.join("btop.conf");

                let hint_no_conf = generator.setup_hint();
                assert!(hint_no_conf.unwrap().contains("btop.conf"));

                fs::create_dir_all(&btop_dir).unwrap();
                fs::write(&btop_conf, "some_setting = true").unwrap();
                let hint_no_key = generator.setup_hint();
                assert!(hint_no_key.unwrap().contains("color_theme ="));

                fs::write(&btop_conf, "color_theme = \"default\"").unwrap();
                assert!(generator.setup_hint().is_none());
            },
        );
    }

    #[test]
    fn should_update_existing_line_or_append() {
        let generator = BtopGenerator;
        let temp_dir: TempDir = TempDir::new("btop_test").unwrap();
        let conf_path = temp_dir.path().join("btop.conf");

        fs::write(
            &conf_path,
            "theme_background = True\ncolor_theme = \"default\"\n",
        )
        .unwrap();
        generator.update_btop_conf(&conf_path, "new-theme").unwrap();
        let content = fs::read_to_string(&conf_path).unwrap();
        assert!(content.contains("color_theme = \"new-theme\""));
        assert!(!content.contains("color_theme = \"default\""));

        fs::write(&conf_path, "theme_background = True\n").unwrap();
        generator
            .update_btop_conf(&conf_path, "only-theme")
            .unwrap();
        let content = fs::read_to_string(&conf_path).unwrap();
        assert!(content.contains("color_theme = \"only-theme\""));
    }

    #[test]
    fn should_apply_theme_and_update_conf() {
        let (tmp_dir, ctx) = create_test_context();
        let generator = BtopGenerator;
        let p = Palette::mock();

        temp_env::with_vars(
            vec![
                ("XDG_CONFIG_HOME", Some(tmp_dir.path())),
                ("HOME", Some(tmp_dir.path())),
            ],
            || {
                let btop_dir = generator
                    .resolve_config_directory()
                    .parent()
                    .unwrap()
                    .to_path_buf();
                let btop_conf = btop_dir.join("btop.conf");

                fs::create_dir_all(&btop_dir).unwrap();
                fs::write(
                    &btop_conf,
                    "graph_symbol = \"braille\"\ncolor_theme = \"old-theme\"\n",
                )
                .unwrap();

                let result = generator.apply(&p, &ctx);
                assert!(result.is_ok());

                let cache_file = ctx.paths.cache.join("btop_themes").join("test-theme.theme");
                assert!(cache_file.exists());

                let updated_content = fs::read_to_string(&btop_conf).unwrap();
                assert!(updated_content.contains(&format!("color_theme = \"{}\"", p.name)));
                assert!(updated_content.contains("graph_symbol = \"braille\""));
            },
        );
    }
}
