mod key;

use crate::modules::tools::rules::key::ColorKey;

pub struct TmRule {
    pub name: &'static str,
    pub scope: &'static str,
    pub style: &'static str,
    pub color_key: ColorKey,
}

pub static RULES: &[TmRule] = &[
    TmRule {
        name: "Basic text and variable names (incl. leading punctuation)",
        scope: "text, source, variable.other.readwrite, punctuation.definition.variable",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Parentheses, Brackets, Braces",
        scope: "punctuation",
        style: "",
        color_key: ColorKey::Comment,
    },
    TmRule {
        name: "Comments",
        scope: "comment, punctuation.definition.comment",
        style: "italic",
        color_key: ColorKey::Comment,
    },
    TmRule {
        name: "",
        scope: "string, punctuation.definition.string",
        style: "",
        color_key: ColorKey::String,
    },
    TmRule {
        name: "",
        scope: "constant.character.escape",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Booleans, constants, numbers",
        scope: "constant.numeric, variable.other.constant, entity.name.constant, constant.language.boolean, constant.language.false, constant.language.true, keyword.other.unit.user-defined, keyword.other.unit.suffix.floating-point",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "",
        scope: "keyword, keyword.operator.word, keyword.operator.new, variable.language.super, support.type.primitive, storage.type, storage.modifier, punctuation.definition.keyword",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "",
        scope: "entity.name.tag.documentation",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Punctuation",
        scope: "keyword.operator, punctuation.accessor, punctuation.definition.generic, meta.function.closure punctuation.section.parameters, punctuation.definition.tag, punctuation.separator.key-value",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "",
        scope: "entity.name.function, meta.function-call.method, support.function, support.function.misc, variable.function",
        style: "italic",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Classes",
        scope: "entity.name.class, entity.other.inherited-class, support.class, meta.function-call.constructor, entity.name.struct",
        style: "italic",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Enum",
        scope: "entity.name.enum",
        style: "italic",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Enum member",
        scope: "meta.enum variable.other.readwrite, variable.other.enummember",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Object properties",
        scope: "meta.property.object",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Types",
        scope: "meta.type, meta.type-alias, support.type, entity.name.type",
        style: "italic",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Decorators",
        scope: "meta.annotation variable.function, meta.annotation variable.annotation.function, meta.annotation punctuation.definition.annotation, meta.decorator, punctuation.decorator",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "",
        scope: "variable.parameter, meta.function.parameters",
        style: "italic",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "Built-ins",
        scope: "constant.language, support.function.builtin",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "",
        scope: "entity.other.attribute-name.documentation",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Preprocessor directives",
        scope: "keyword.control.directive, punctuation.definition.directive",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Type parameters",
        scope: "punctuation.definition.typeparameters",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Namespaces",
        scope: "entity.name.namespace",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Property names (left hand assignments in json/yaml/css)",
        scope: "support.type.property-name.css",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "This/Self keyword",
        scope: "variable.language.this, variable.language.this punctuation.definition.variable",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Object properties",
        scope: "variable.object.property",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "String template interpolation",
        scope: "string.template variable, string variable",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "C++ extern keyword",
        scope: "storage.modifier.specifier.extern.cpp",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "C++ scope resolution",
        scope: "entity.name.scope-resolution.template.call.cpp, entity.name.scope-resolution.parameter.cpp, entity.name.scope-resolution.cpp, entity.name.scope-resolution.function.definition.cpp",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "C++ operators",
        scope: "storage.modifier.reference.cpp",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "C# Interpolated Strings",
        scope: "meta.interpolation.cs",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "C# xml-style docs",
        scope: "comment.block.documentation.cs",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Classes, reflecting the className color in JSX",
        scope: "source.css entity.other.attribute-name.class.css, entity.other.attribute-name.parent-selector.css punctuation.definition.entity.css",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Operators",
        scope: "punctuation.separator.operator.css",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Pseudo classes",
        scope: "source.css entity.other.attribute-name.pseudo-class",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "",
        scope: "source.css constant.other.unicode-range",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "",
        scope: "source.css variable.parameter.url",
        style: "",
        color_key: ColorKey::String,
    },
    TmRule {
        name: "CSS vendored property names",
        scope: "support.type.vendored.property-name",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Less/SCSS right-hand variables",
        scope: "source.css meta.property-value variable, source.css meta.property-value variable.other.less, source.css meta.property-value variable.other.less punctuation.definition.variable.less, meta.definition.variable.scss",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "CSS variables (--prefixed)",
        scope: "source.css meta.property-list variable, meta.property-list variable.other.less, meta.property-list variable.other.less punctuation.definition.variable.less",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "CSS Percentage values, styled the same as numbers",
        scope: "keyword.other.unit.percentage.css",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "CSS Attribute selectors, styled the same as strings",
        scope: "source.css meta.attribute-selector",
        style: "",
        color_key: ColorKey::String,
    },
    TmRule {
        name: "JSON/YAML keys, other left-hand assignments",
        scope: "keyword.other.definition.ini, punctuation.support.type.property-name.json, support.type.property-name.json, punctuation.support.type.property-name.toml, support.type.property-name.toml, entity.name.tag.yaml, punctuation.support.type.property-name.yaml, support.type.property-name.yaml",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "JSON/YAML constants",
        scope: "constant.language.json, constant.language.yaml",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "YAML anchors",
        scope: "entity.name.type.anchor.yaml, variable.other.alias.yaml",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "TOML tables / ini groups",
        scope: "support.type.property-name.table, entity.name.section.group-title.ini",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "TOML dates",
        scope: "constant.other.time.datetime.offset.toml",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "YAML anchor puctuation",
        scope: "punctuation.definition.anchor.yaml, punctuation.definition.alias.yaml",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "YAML triple dashes",
        scope: "entity.other.document.begin.yaml",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Markup Diff",
        scope: "markup.changed.diff",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Diff",
        scope: "meta.diff.header.from-file, meta.diff.header.to-file, punctuation.definition.from-file.diff, punctuation.definition.to-file.diff",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Diff Inserted",
        scope: "markup.inserted.diff",
        style: "",
        color_key: ColorKey::String,
    },
    TmRule {
        name: "Diff Deleted",
        scope: "markup.deleted.diff",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "dotenv left-hand side assignments",
        scope: "variable.other.env",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "dotenv reference to existing env variable",
        scope: "string.quoted variable.other.env",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "GDScript functions",
        scope: "support.function.builtin.gdscript",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "GDScript constants",
        scope: "constant.language.gdscript",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Comment keywords",
        scope: "comment meta.annotation.go",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "go:embed, go:build, etc.",
        scope: "comment meta.annotation.parameters.go",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Go constants (nil, true, false)",
        scope: "constant.language.go",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "GraphQL variables",
        scope: "variable.graphql",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "GraphQL aliases",
        scope: "string.unquoted.alias.graphql",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "GraphQL enum members",
        scope: "constant.character.enum.graphql",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "GraphQL field in types",
        scope: "meta.objectvalues.graphql constant.object.key.graphql string.unquoted.graphql",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "HTML/XML DOCTYPE as keyword",
        scope: "keyword.other.doctype, meta.tag.sgml.doctype punctuation.definition.tag, meta.tag.metadata.doctype entity.name.tag, meta.tag.metadata.doctype punctuation.definition.tag",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "HTML/XML-like tags",
        scope: "entity.name.tag",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Special characters like ampersand",
        scope: "text.html constant.character.entity, text.html constant.character.entity punctuation, constant.character.entity.xml, constant.character.entity.xml punctuation, constant.character.entity.js.jsx, constant.charactger.entity.js.jsx punctuation, constant.character.entity.tsx, constant.character.entity.tsx punctuation",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "HTML/XML tag attribute values",
        scope: "entity.other.attribute-name",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Components",
        scope: "support.class.component, support.class.component.jsx, support.class.component.tsx, support.class.component.vue",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Annotations",
        scope: "punctuation.definition.annotation, storage.type.annotation",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Java enums",
        scope: "constant.other.enum.java",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Java imports",
        scope: "storage.modifier.import.java",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Exported Variable",
        scope: "meta.export variable.other.readwrite.js",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "JS/TS constants and properties",
        scope: "variable.other.constant.js, variable.other.constant.ts, variable.other.property.js, variable.other.property.ts",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "JSDoc; these are mainly params, so styled as such",
        scope: "variable.other.jsdoc, comment.block.documentation variable.other",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "",
        scope: "support.type.object.console.js",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Node constants as keywords (module, etc.)",
        scope: "support.constant.node, support.type.object.module.js",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "implements as keyword",
        scope: "storage.modifier.implements",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Builtin types",
        scope: "constant.language.null.js, constant.language.null.ts, constant.language.undefined.js, constant.language.undefined.ts, support.type.builtin.ts",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "",
        scope: "variable.parameter.generic",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Arrow functions",
        scope: "keyword.declaration.function.arrow.js, storage.type.function.arrow.ts",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Decorator punctuations (decorators inherit from blue functions, instead of styleguide peach)",
        scope: "punctuation.decorator.ts",
        style: "italic",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Extra JS/TS keywords",
        scope: "keyword.operator.expression.in.js, keyword.operator.expression.in.ts, keyword.operator.expression.infer.ts, keyword.operator.expression.instanceof.js, keyword.operator.expression.instanceof.ts, keyword.operator.expression.is, keyword.operator.expression.keyof.ts, keyword.operator.expression.of.js, keyword.operator.expression.of.ts, keyword.operator.expression.typeof.ts",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Julia macros",
        scope: "support.function.macro.julia",
        style: "italic",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Julia language constants (true, false)",
        scope: "constant.language.julia",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Julia other constants (these seem to be arguments inside arrays)",
        scope: "constant.other.symbol.julia",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "LaTeX preamble",
        scope: "text.tex keyword.control.preamble",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "LaTeX be functions",
        scope: "text.tex support.function.be",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "LaTeX math",
        scope: "constant.other.general.math.tex",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "Liquid Builtin Objects and User Defined Variables",
        scope: "variable.language.liquid",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Lua docstring keywords",
        scope: "comment.line.double-dash.documentation.lua storage.type.annotation.lua",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Lua docstring variables",
        scope: "comment.line.double-dash.documentation.lua entity.name.variable.lua, comment.line.double-dash.documentation.lua variable.lua",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "",
        scope: "heading.1.markdown punctuation.definition.heading.markdown, heading.1.markdown, heading.1.quarto punctuation.definition.heading.quarto, heading.1.quarto, markup.heading.atx.1.mdx, markup.heading.atx.1.mdx punctuation.definition.heading.mdx, markup.heading.setext.1.markdown, markup.heading.heading-0.asciidoc",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "",
        scope: "heading.2.markdown punctuation.definition.heading.markdown, heading.2.markdown, heading.2.quarto punctuation.definition.heading.quarto, heading.2.quarto, markup.heading.atx.2.mdx, markup.heading.atx.2.mdx punctuation.definition.heading.mdx, markup.heading.setext.2.markdown, markup.heading.heading-1.asciidoc",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "",
        scope: "heading.3.markdown punctuation.definition.heading.markdown, heading.3.markdown, heading.3.quarto punctuation.definition.heading.quarto, heading.3.quarto, markup.heading.atx.3.mdx, markup.heading.atx.3.mdx punctuation.definition.heading.mdx, markup.heading.heading-2.asciidoc",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "",
        scope: "heading.4.markdown punctuation.definition.heading.markdown, heading.4.markdown, heading.4.quarto punctuation.definition.heading.quarto, heading.4.quarto, markup.heading.atx.4.mdx, markup.heading.atx.4.mdx punctuation.definition.heading.mdx, markup.heading.heading-3.asciidoc",
        style: "",
        color_key: ColorKey::String,
    },
    TmRule {
        name: "",
        scope: "heading.5.markdown punctuation.definition.heading.markdown, heading.5.markdown, heading.5.quarto punctuation.definition.heading.quarto, heading.5.quarto, markup.heading.atx.5.mdx, markup.heading.atx.5.mdx punctuation.definition.heading.mdx, markup.heading.heading-4.asciidoc",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "",
        scope: "heading.6.markdown punctuation.definition.heading.markdown, heading.6.markdown, heading.6.quarto punctuation.definition.heading.quarto, heading.6.quarto, markup.heading.atx.6.mdx, markup.heading.atx.6.mdx punctuation.definition.heading.mdx, markup.heading.heading-5.asciidoc",
        style: "",
        color_key: ColorKey::Variable,
    },
    TmRule {
        name: "",
        scope: "markup.bold",
        style: "bold",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "",
        scope: "markup.italic",
        style: "italic",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "",
        scope: "markup.strikethrough",
        style: "strikethrough",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Markdown auto links",
        scope: "punctuation.definition.link, markup.underline.link",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Markdown links",
        scope: "text.html.markdown punctuation.definition.link.title, text.html.quarto punctuation.definition.link.title, string.other.link.title.markdown, string.other.link.title.quarto, markup.link, punctuation.definition.constant.markdown, punctuation.definition.constant.quarto, constant.other.reference.link.markdown, constant.other.reference.link.quarto, markup.substitution.attribute-reference",
        style: "",
        color_key: ColorKey::Variable,
    },
    TmRule {
        name: "Markdown code spans",
        scope: "punctuation.definition.raw.markdown, punctuation.definition.raw.quarto, markup.inline.raw.string.markdown, markup.inline.raw.string.quarto, markup.raw.block.markdown, markup.raw.block.quarto",
        style: "",
        color_key: ColorKey::String,
    },
    TmRule {
        name: "Markdown triple backtick language identifier",
        scope: "fenced_code.block.language",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Markdown triple backticks",
        scope: "markup.fenced_code.block punctuation.definition, markup.raw support.asciidoc",
        style: "",
        color_key: ColorKey::Comment,
    },
    TmRule {
        name: "Markdown quotes",
        scope: "markup.quote, punctuation.definition.quote.begin",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Markdown separators",
        scope: "meta.separator.markdown",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Markdown list bullets",
        scope: "punctuation.definition.list.begin.markdown, punctuation.definition.list.begin.quarto, markup.list.bullet",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Nix attribute names",
        scope: "entity.other.attribute-name.multipart.nix, entity.other.attribute-name.single.nix",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Nix parameter names",
        scope: "variable.parameter.name.nix",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Nix interpolated parameter names",
        scope: "meta.embedded variable.parameter.name.nix",
        style: "",
        color_key: ColorKey::Variable,
    },
    TmRule {
        name: "Nix paths",
        scope: "string.unquoted.path.nix",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "PHP Attributes",
        scope: "support.attribute.builtin, meta.attribute.php",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "PHP Parameters (needed for the leading dollar sign)",
        scope: "meta.function.parameters.php punctuation.definition.variable.php",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "PHP Constants",
        scope: "constant.language.php",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "PHP functions",
        scope: "text.html.php support.function",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Python argument functions reset to text, otherwise they inherit blue from function-call",
        scope: "support.variable.magic.python, meta.function-call.arguments.python",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Python double underscore functions",
        scope: "support.function.magic.python",
        style: "italic",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Python `self` keyword",
        scope: "variable.parameter.function.language.special.self.python, variable.language.special.self.python",
        style: "italic",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "python keyword flow/logical (for ... in)",
        scope: "keyword.control.flow.python, keyword.operator.logical.python",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "python storage type",
        scope: "storage.type.function.python",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "python function support",
        scope: "support.token.decorator.python, meta.function.decorator.identifier.python",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "python function calls",
        scope: "meta.function-call.python",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "python function decorators",
        scope: "entity.name.function.decorator.python, punctuation.definition.decorator.python",
        style: "italic",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "python placeholder reset to normal string",
        scope: "constant.character.format.placeholder.other.python",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Python exception and builtins such as exit()",
        scope: "support.type.exception.python, support.function.builtin.python",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "entity.name.type",
        scope: "support.type.python",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "python constants (True/False)",
        scope: "constant.language.python",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Arguments accessed later in the function body",
        scope: "meta.indexed-name.python, meta.item-access.python",
        style: "italic",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "Python f-strings/binary/unicode storage types",
        scope: "storage.type.string.python",
        style: "italic",
        color_key: ColorKey::String,
    },
    TmRule {
        name: "Regex string begin/end in JS/TS",
        scope: "string.regexp punctuation.definition.string.begin, string.regexp punctuation.definition.string.end",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Regex anchors",
        scope: "keyword.control.anchor.regexp",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Regex regular string match",
        scope: "string.regexp.ts",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Regex group parenthesis and backreference",
        scope: "punctuation.definition.group.regexp, keyword.other.back-reference.regexp",
        style: "",
        color_key: ColorKey::String,
    },
    TmRule {
        name: "Regex character class []",
        scope: "punctuation.definition.character-class.regexp",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Regex character classes",
        scope: "constant.other.character-class.regexp",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Regex range",
        scope: "constant.other.character-class.range.regexp",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "Regex quantifier",
        scope: "keyword.operator.quantifier.regexp",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Regex constant/numeric",
        scope: "constant.character.numeric.regexp",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Regex lookaheads, negative lookaheads, lookbehinds, negative lookbehinds",
        scope: "punctuation.definition.group.no-capture.regexp, meta.assertion.look-ahead.regexp, meta.assertion.negative-look-ahead.regexp",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Rust attribute",
        scope: "meta.annotation.rust, meta.annotation.rust punctuation, meta.attribute.rust, punctuation.definition.attribute.rust",
        style: "italic",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Rust keyword",
        scope: "entity.name.function.macro.rules.rust, storage.type.module.rust, storage.modifier.rust, storage.type.struct.rust, storage.type.enum.rust, storage.type.trait.rust, storage.type.union.rust, storage.type.impl.rust, storage.type.rust, storage.type.function.rust, storage.type.type.rust",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Rust u/i32, u/i64, etc.",
        scope: "entity.name.type.numeric.rust",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Rust generic",
        scope: "meta.generic.rust",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Rust impl",
        scope: "entity.name.impl.rust",
        style: "italic",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Rust module",
        scope: "entity.name.module.rust",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Rust trait",
        scope: "entity.name.trait.rust",
        style: "italic",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Rust struct",
        scope: "storage.type.source.rust",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Rust union",
        scope: "entity.name.union.rust",
        style: "",
        color_key: ColorKey::TypeName,
    },
    TmRule {
        name: "Rust enum member",
        scope: "meta.enum.rust storage.type.source.rust",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Rust macro",
        scope: "support.macro.rust, meta.macro.rust support.function.rust, entity.name.function.macro.rust",
        style: "italic",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Rust lifetime",
        scope: "storage.modifier.lifetime.rust, entity.name.type.lifetime",
        style: "italic",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Rust string formatting",
        scope: "string.quoted.double.rust constant.other.placeholder.rust",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Rust return type generic",
        scope: "meta.function.return-type.rust meta.generic.rust storage.type.rust",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Rust functions",
        scope: "meta.function.call.rust",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Rust angle brackets",
        scope: "punctuation.brackets.angle.rust",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "Rust constants",
        scope: "constant.other.caps.rust",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "Rust function parameters",
        scope: "meta.function.definition.rust variable.other.rust",
        style: "",
        color_key: ColorKey::Attribute,
    },
    TmRule {
        name: "Rust closure variables",
        scope: "meta.function.call.rust variable.other.rust",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Rust self",
        scope: "variable.language.self.rust",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Rust metavariable names",
        scope: "variable.other.metavariable.name.rust, meta.macro.metavariable.rust keyword.operator.macro.dollar.rust",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Shell shebang",
        scope: "comment.line.shebang, comment.line.shebang punctuation.definition.comment, comment.line.shebang, punctuation.definition.comment.shebang.shell, meta.shebang.shell",
        style: "italic",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Shell shebang command",
        scope: "comment.line.shebang constant.language",
        style: "italic",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Shell interpolated command",
        scope: "meta.function-call.arguments.shell punctuation.definition.variable.shell, meta.function-call.arguments.shell punctuation.section.interpolation, meta.function-call.arguments.shell punctuation.definition.variable.shell, meta.function-call.arguments.shell punctuation.section.interpolation",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Shell interpolated command variable",
        scope: "meta.string meta.interpolation.parameter.shell variable.other.readwrite",
        style: "italic",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "",
        scope: "source.shell punctuation.section.interpolation, punctuation.definition.evaluation.backticks.shell",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "Shell EOF",
        scope: "entity.name.tag.heredoc.shell",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "Shell quoted variable",
        scope: "string.quoted.double.shell variable.other.normal.shell",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "",
        scope: "markup.heading.typst",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "JSON Keys",
        scope: "source.json meta.mapping.key string",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "JSON key surrounding quotes",
        scope: "source.json meta.mapping.key punctuation.definition.string.begin, source.json meta.mapping.key punctuation.definition.string.end",
        style: "",
        color_key: ColorKey::Comment,
    },
    TmRule {
        name: "",
        scope: "markup.heading.synopsis.man, markup.heading.title.man, markup.heading.other.man, markup.heading.env.man",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "",
        scope: "markup.heading.commands.man",
        style: "",
        color_key: ColorKey::Func,
    },
    TmRule {
        name: "",
        scope: "markup.heading.env.man",
        style: "",
        color_key: ColorKey::Fg,
    },
    TmRule {
        name: "Man page options",
        scope: "entity.name",
        style: "",
        color_key: ColorKey::Operator,
    },
    TmRule {
        name: "",
        scope: "markup.heading.1.markdown",
        style: "",
        color_key: ColorKey::Keyword,
    },
    TmRule {
        name: "",
        scope: "markup.heading.2.markdown",
        style: "",
        color_key: ColorKey::Number,
    },
    TmRule {
        name: "",
        scope: "markup.heading.markdown",
        style: "",
        color_key: ColorKey::TypeName,
    },
];
