/// Build config theme for ghostty
pub fn build_ghostty_config(p: &crate::models::Palette, name: &str) -> String {
    let mut cfg = String::new();
    cfg.push_str(&format!("# Theme: {}, generated by Iris\n\n", name));

    cfg.push_str(&format!("background = {}\n", p.bg));
    cfg.push_str(&format!("foreground = {}\n", p.fg));
    cfg.push_str(&format!("cursor-color = {}\n", p.white));
    cfg.push_str(&format!("selection-background = {}\n", p.sel));
    cfg.push_str(&format!("selection-foreground = {}\n\n", p.bg));

    for (idx, color) in p.ansi.iter().enumerate() {
        cfg.push_str(&format!("palette = {}={}\n", idx, color));
    }

    cfg
}
