-- Automatically generated by Iris. DO NOT EDIT.

vim.api.nvim_create_autocmd("ColorScheme", {
    desc = "Notify Iris about theme change",
    callback = function()
        local theme = vim.g.colors_name
        if theme then
            local cache_dir = vim.fn.stdpath("cache")
            local f = io.open(cache_dir .. "/iris_current_theme", "w")
            if f then
                f:write(theme)
                f:close()
            end
        end
    end,
})
