use crate::{
    core::IrisContext,
    models::Palette,
    modules::{Generator, GeneratorType},
    utils,
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for yazi
pub struct YaziGenerator;

impl Generator for YaziGenerator {
    fn name(&self) -> &str {
        "yazi"
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::Tool
    }

    fn target_file_name(&self, _theme: &str) -> String {
        "theme.toml".into()
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let theme_name: &String = &p.name;

        let yazi_dir: PathBuf = self.resolve_config_directory();
        if !yazi_dir.exists() {
            ctx.log
                .info(&format!("Creating {} config directory...", "yazi".bold()));
            fs::create_dir_all(&yazi_dir)?;
        }

        let cache_file: PathBuf = ctx
            .paths
            .cache
            .join(format!("yazi_themes/{}.toml", theme_name));
        let theme_link: PathBuf = yazi_dir.join(self.target_file_name(theme_name));

        let content: String = self.build_config(p);

        fs::create_dir_all(cache_file.parent().unwrap())?;
        fs::write(&cache_file, content)?;
        ctx.log.info(&format!(
            "Theme {} generated in cache.",
            utils::capitalize(theme_name).yellow()
        ));

        if theme_link.exists() || theme_link.is_symlink() {
            fs::remove_file(&theme_link)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            ctx.log.info(&format!(
                "Linking theme.toml to {} config...",
                "yazi".bold()
            ));
            symlink(&cache_file, &theme_link).with_context(|| {
                format!(
                    "Failed to create symlink {:?} -> {:?}",
                    theme_link, cache_file
                )
            })?;
        }

        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let yazi_dir: PathBuf = self.resolve_config_directory();

        if !yazi_dir.exists() {
            return Some(format!(
                "No {} found — make sure Yazi is installed and run it once to initialize config.",
                yazi_dir.display().to_string().cyan(),
            ));
        }

        None
    }
}

impl YaziGenerator {
    /// Build yazi theme
    fn build_config(&self, p: &Palette) -> String {
        let red = &p.ansi[1];
        let green = &p.ansi[2];
        let orange = &p.ansi[3];
        let blue = &p.ansi[4];
        let magenta = &p.ansi[5];
        let teal = &p.ansi[6];
        let tan = &p.ansi[7];

        let br_red = &p.ansi[9];
        let br_green = &p.ansi[10];
        let br_orange = &p.ansi[11];
        let br_blue = &p.ansi[12];
        let br_magenta = &p.ansi[13];
        let br_teal = &p.ansi[14];

        let line_hl = if p.line_hl == "#cccccc" {
            &p.sel
        } else {
            &p.line_hl
        };

        format!(
            r#"# Theme: {name}, generated by Iris
# vim:fileencoding=utf-8:foldmethod=marker

[manager]
cwd = {{ fg = "{br_red}", bold = true }}

hovered         = {{ fg = "{bg}", bg = "{orange}", bold = true }}
preview_hovered = {{ underline = true }}
symlink_target = {{ fg = "{gutter_fg}" }}

find_keyword  = {{ fg = "{br_orange}", bold = true }}
find_position = {{ fg = "{br_magenta}" }}

marker_selected = {{ fg = "{br_green}", bold = true }}
marker_copied   = {{ fg = "{br_orange}", bold = true }}
marker_cut      = {{ fg = "{br_red}", bold = true }}

tab_active   = {{ fg = "{bg}", bg = "{teal}", bold = true }}
tab_inactive = {{ fg = "{tan}", bg = "{line_hl}" }}
tab_width    = 1

border_symbol = "│"
border_style  = {{ fg = "{tan}" }}

[status]
separator_open  = ""
separator_close = ""
separator_style = {{ fg = "{line_hl}", bg = "{line_hl}" }}

mode_normal = {{ fg = "{bg}", bg = "{br_teal}",    bold = true }}
mode_select = {{ fg = "{bg}", bg = "{br_green}",   bold = true }}
mode_unset  = {{ fg = "{bg}", bg = "{br_magenta}", bold = true }}

filename   = {{ fg = "{white}", bold = true }}
filesize   = {{ fg = "{tan}" }}
permissions = {{ fg = "{comment}" }}

progress_label  = {{ fg = "{br_orange}", bold = true }}
progress_normal = {{ fg = "{teal}" }}
progress_error  = {{ fg = "{red}" }}

permissions_t = {{ fg = "{br_teal}" }}
permissions_r = {{ fg = "{br_orange}" }}
permissions_w = {{ fg = "{red}" }}
permissions_x = {{ fg = "{br_green}" }}
permissions_s = {{ fg = "{tan}" }}

[filetype]
rules = [
  {{ name = "*/",                           fg = "{br_green}", bold = true }},

  {{ mime = "text/x-shellscript",           fg = "{green}", bold = true }},

  {{ mime = "image/*",                      fg = "{br_teal}" }},
  {{ mime = "video/*",                      fg = "{br_orange}" }},
  {{ mime = "audio/*",                      fg = "{magenta}" }},

  {{ mime = "application/zip",              fg = "{br_magenta}" }},
  {{ mime = "application/gzip",             fg = "{br_magenta}" }},
  {{ mime = "application/x-tar",            fg = "{br_magenta}" }},
  {{ mime = "application/x-7z-compressed",  fg = "{br_magenta}" }},
  {{ mime = "application/x-rar-compressed", fg = "{br_magenta}" }},
  {{ mime = "application/zstd",             fg = "{br_magenta}" }},

  {{ mime = "application/pdf",              fg = "{red}", bold = true }},
  {{ mime = "text/markdown",                fg = "{br_orange}", italic = true }},
  {{ mime = "text/html",                    fg = "{orange}" }},
  {{ mime = "application/json",             fg = "{br_green}" }},
  {{ mime = "text/csv",                     fg = "{green}" }},

  {{ mime = "text/x-python",                fg = "{br_blue}" }},
  {{ mime = "text/x-rust",                  fg = "{br_red}" }},
  {{ mime = "text/x-c",                     fg = "{blue}" }},
  {{ mime = "text/javascript",              fg = "{br_orange}" }},
  {{ mime = "text/typescript",              fg = "{blue}" }},
  {{ mime = "text/x-go",                    fg = "{teal}" }},

  {{ name = "*.toml",                       fg = "{tan}" }},
  {{ name = "*.yaml",                       fg = "{tan}" }},
  {{ name = "*.yml",                        fg = "{tan}" }},
  {{ name = "*.env",                        fg = "{br_green}", bold = true }},
  {{ name = "*.lock",                       fg = "{gutter_fg}" }},
  {{ name = ".gitignore",                   fg = "{gutter_fg}" }},
  {{ name = "Makefile",                     fg = "{br_red}", bold = true }},
  {{ name = "Dockerfile",                   fg = "{blue}", bold = true }},
  {{ name = "README*",                      fg = "{br_orange}", bold = true }},
  {{ name = "LICENSE*",                     fg = "{tan}" }},

  {{ name = "*",                            fg = "{fg}" }},
]

[icon]
conds = [
  {{ if = "dir & hovered", text = "",  fg = "{bg}",  bg = "{orange}" }},
  {{ if = "dir",           text = "",  fg = "{br_green}" }},
  {{ if = "link & hovered",text = "",  fg = "{bg}",  bg = "{teal}" }},
  {{ if = "link",          text = "",  fg = "{teal}" }},
  {{ if = "exec",          text = "",  fg = "{br_green}" }},
  {{ if = "orphan",        text = "",  fg = "{red}" }},
  {{ if = "!dir",          text = "",  fg = "{fg}" }},
]
"#,
            name = utils::capitalize(&p.name),
            bg = p.bg,
            fg = p.fg,
            white = p.white,
            comment = p.comment,
            tan = tan,
            line_hl = line_hl,
            gutter_fg = p.gutter_fg,
            orange = orange,
            green = green,
            red = red,
            magenta = magenta,
            teal = teal,
            blue = blue,
            br_red = br_red,
            br_green = br_green,
            br_orange = br_orange,
            br_blue = br_blue,
            br_magenta = br_magenta,
            br_teal = br_teal,
        )
    }
}

/// Unit-tests for yazi generator
#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::create_test_context;
    use temp_env;
    use tempdir::TempDir;

    #[test]
    fn should_return_yazi_metadata() {
        let generator = YaziGenerator;
        assert_eq!(generator.name(), "yazi");
        assert_eq!(generator.generator_type(), GeneratorType::Tool);
        assert_eq!(generator.target_file_name("any"), "theme.toml");
    }

    #[test]
    fn should_handle_yazi_build_config_interpolation() {
        let generator = YaziGenerator;
        let p = Palette::mock();
        let config = generator.build_config(&p);

        assert!(config.contains("Theme: Test-theme"));
        assert!(config.contains("#1a1b26"));
        assert!(config.contains("#f7768e"));
    }

    #[test]
    fn should_generate_setup_hint_for_yazi() {
        let generator = YaziGenerator;
        let temp_dir: TempDir = TempDir::new("yazi_hint").unwrap();
        let fake_config_root = temp_dir.path().join("config");
        fs::create_dir_all(&fake_config_root).unwrap();

        temp_env::with_vars(
            vec![
                ("XDG_CONFIG_HOME", Some(&fake_config_root)),
                ("HOME", Some(&temp_dir.into_path())),
            ],
            || {
                let resolved = generator.resolve_config_directory();
                println!("DEBUG: resolved path: {:?}", resolved);

                let hint = generator.setup_hint();
                assert!(
                    hint.is_some(),
                    "Hint should be Some for path: {:?}",
                    resolved
                );

                fs::create_dir_all(&resolved).unwrap();
                assert!(generator.setup_hint().is_none());
            },
        );
    }

    #[test]
    fn should_apply_theme_for_yazi() {
        if which::which("yazi").is_err() {
            return;
        }

        let (tmp_dir, ctx) = create_test_context();
        let generator = YaziGenerator;
        let p = Palette::mock();

        temp_env::with_vars(
            vec![
                ("XDG_CONFIG_HOME", Some(tmp_dir.path())),
                ("HOME", Some(tmp_dir.path())),
            ],
            || {
                let result = generator.apply(&p, &ctx);
                assert!(result.is_ok());

                let expected_yazi_dir = generator.resolve_config_directory();
                let yazi_theme_link = expected_yazi_dir.join("theme.toml");

                assert!(
                    yazi_theme_link.exists(),
                    "Symlink missing at {:?}. Check if resolve_config_directory is consistent!",
                    yazi_theme_link
                );
            },
        );
    }
}
