use crate::{
    core::IrisContext, infra::NeovimBridge, log::Activity, models::PluginManager,
    service::ThemeService, utils,
};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Struct for initializing state of application
pub struct IrisSetup;

impl IrisSetup {
    pub fn run(ctx: &mut IrisContext) -> anyhow::Result<()> {
        if ctx.log.is_detailed() {
            eprintln!();
            eprintln!("{}  {}", "󰒓".purple().bold(), "Iris initialization".bold());
        }
        eprintln!();

        ctx.log
            .action("Infrastructure prepared", || ctx.paths.ensure_dirs())?;
        if ctx.log.is_detailed() {
            eprintln!();
        }

        {
            let task =
                ctx.log
                    .step_with_icon(&"󰏘".red().bold(), "Initializing application state", false);
            Self::setup_initial_state(ctx, &task)?;
            task.done_with("System state initialized");
        }

        {
            let task = ctx
                .log
                .step_with_icon(&"󰒓".green().bold(), "Integrating with Neovim", true);
            Self::setup_nvim_automation(ctx, &task)?;
            task.done_with("Neovim automation hook generated smoothly");
        }

        ctx.log
            .success("Iris is now fully configured and ready to go!");
        eprintln!();

        Ok(())
    }

    /// Initializes state
    fn setup_initial_state(ctx: &mut IrisContext, task: &Activity) -> anyhow::Result<()> {
        if ctx.paths.state_file.exists() {
            task.info("Found existing state.toml, loading configuration.");
            return Ok(());
        }

        task.info("Detecting Neovim plugin manager...");
        let manager: PluginManager = NeovimBridge::detect(&ctx.paths);

            task.info(&format!(
                "Found {} with {} plugins installed.",
        if !manager.is_default() {
            let count: usize = NeovimBridge::count(&ctx.paths, &manager);
                manager,
                count.to_string().yellow().bold()
            ));
        }

        ctx.state.nvim.manager = manager;
        task.info("Detecting active Neovim theme...");

        let service: ThemeService<'_> = ThemeService::new(&ctx.paths, &activity.log);
        let current_theme: String = service.current().unwrap_or_else(|_| "".to_string());

        task.info("Scanning for compatible tools...");
        let installed = ctx.registry.installed();

        if installed.is_empty() {
            task.info("No compatible tools found.");
        } else {
            for generator in installed.iter() {
                task.info(&format!("Found: {}", generator.name().green().bold()));
                ctx.state.enable_generator(generator.name());
            }
        }

        ctx.state.set_theme(current_theme);
        ctx.save()?;

        task.info(&format!(
            "Configuration persisted to {}",
            utils::pretty_path(&ctx.paths.state_file).dimmed()
        ));
        Ok(())
    }

    /// Generates Neovim site plugin script for automatic synchronization
    fn setup_nvim_automation(ctx: &IrisContext, task: &Activity) -> anyhow::Result<()> {
        let nvim_plugin_dir: PathBuf = ctx.paths.nvim_data_dir().join("site/plugin");
        let nvim_plugin_dir: PathBuf = ctx.paths.nvim_data_path().join("site/plugin");
        let plugin_file: PathBuf = nvim_plugin_dir.join("iris_sync.lua");

        let lua_code = r#"-- Automatically generated by Iris. DO NOT EDIT.
vim.api.nvim_create_autocmd("ColorScheme", {
    desc = "Notify Iris about theme change",
    callback = function()
        local theme = vim.g.colors_name
        if theme then
            local cache_dir = vim.fn.stdpath("cache")
            local f = io.open(cache_dir .. "/iris_current_theme", "w")
            if f then
                f:write(theme)
                f:close()
            end
        end
    end,
})
"#;

        if plugin_file.exists() {
            if let Ok(existing_content) = fs::read_to_string(&plugin_file) {
                if existing_content == lua_code {
                    task.info("Neovim integration is already up to date.");
                    return Ok(());
                }
            }
        }

        task.info("Writing Neovim autoloader plugin...");
        fs::create_dir_all(&nvim_plugin_dir)?;
        fs::write(&plugin_file, lua_code)?;

        task.info(&format!(
            "Automation persisted to {}",
            crate::utils::pretty_path(&plugin_file).dimmed()
        ));

        Ok(())
    }

    /// Generates initializing script right into stdout for eval
    pub fn emit_zsh_hook(ctx: &IrisContext) -> anyhow::Result<()> {
        let cache_file: PathBuf = ctx.paths.cache.join("fzf.sh");

        let hook: String = format!(
            r#"# --- Iris Dynamic Shell Integration ---

_iris_completion() {{
    local line state
    _arguments -C \
        '1: :->command' \
        '*:: :->args'

    case "$state" in
        args)
            case "$line[1]" in
                switch|preview)
                    _arguments '1:theme:($(iris complete-list 2>/dev/null))'
                    ;;
                apply)
                    _arguments \
                        '(-t --theme)'{{-t,--theme}}'[Override active theme]:theme:($(iris complete-list 2>/dev/null))' \
                        '(-b --fallback)'{{-b,--fallback}}'[Use fallback theme]'
            ;;
        esac
    ;;
esac
}}
compdef _iris_completion iris

autoload -Uz add-zsh-hook
_iris_fzf_sync() {{
    local cache_file="{}"
    if [[ -f "$cache_file" ]]; then
        local mt=$(stat -f %m "$cache_file" 2>/dev/null || stat -c %Y "$cache_file" 2>/dev/null)
        if [[ "$mt" != "$LAST_IRIS_SYNC" ]]; then
            source "$cache_file"
            export LAST_IRIS_SYNC="$mt"
        fi
    fi
}}
add-zsh-hook precmd _iris_fzf_sync
"#,
            cache_file.display()
        );

        println!("{}", hook.trim());
        Ok(())
    }
}

/// Unit-tests for setup
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn should_generate_zsh_hook_correctly() {
        let (_tmp, ctx) = IrisContext::mock();
        let fzf_cache = ctx.paths.cache.join("fzf.sh");
        let cache_str = fzf_cache.display().to_string();

        assert!(cache_str.contains("fzf.sh"));
    }

    #[test]
    fn should_skip_initial_setup_if_exists() {
        let (_tmp, mut ctx) = IrisContext::mock();

        fs::write(
            &ctx.paths.state_file,
            r#"{"current_theme": "nord", "enabled_generators": []}"#,
        )
        .unwrap();

        let task = ctx.log.step("Initial State Test", true);
        let result = IrisSetup::setup_initial_state(&mut ctx, &task);

        assert!(result.is_ok());
    }

    #[test]
    fn should_handle_full_setup_logic() {
        let (tmp, mut ctx) = IrisContext::mock();
        let fake_home = tmp.path();

        temp_env::with_vars(
            [
                ("HOME", Some(fake_home.to_str().unwrap())),
                (
                    "XDG_CONFIG_HOME",
                    Some(fake_home.join(".config").to_str().unwrap()),
                ),
                (
                    "XDG_DATA_HOME",
                    Some(fake_home.join(".local/share").to_str().unwrap()),
                ),
            ],
            || {
                let result = IrisSetup::run(&mut ctx);
                assert!(result.is_ok(), "Setup run failed: {:?}", result.err());
                assert!(ctx.paths.config.exists(), "Config dir should be created");
                assert!(ctx.paths.cache.exists(), "Cache dir should be created");
                assert!(
                    ctx.paths.state_file.exists(),
                    "state file should be created"
                );

                let expected_lua_path =
                    ctx.paths.nvim_data_path().join("site/plugin/iris_sync.lua");
                assert!(
                    expected_lua_path.exists(),
                    "Neovim autoloader script should be generated at {:?}",
                    expected_lua_path
                );

                assert_eq!(ctx.state.nvim.manager, PluginManager::Default);
            },
        );
    }
}
