use crate::{
    core::IrisContext,
    models::Palette,
    modules::{Generator, GeneratorType},
    utils::{self},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for Alacritty terminal
pub struct AlacrittyGenerator;

impl Generator for AlacrittyGenerator {
    fn name(&self) -> &str {
        "alacritty"
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::Terminal
    }

    fn target_file_name(&self, _theme: &str) -> String {
        "current_theme.toml".into()
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let alacritty_dir: PathBuf = self.resolve_config_directory();
        let theme_file_name: String = self.target_file_name("");
        let cache_file: PathBuf = ctx.paths.cache.join("alacritty").join(&theme_file_name);
        let link_path: PathBuf = alacritty_dir.join(&theme_file_name);

        let config_content: String =
            self.build_config(p, &utils::capitalize(&ctx.state.current_theme));
        fs::create_dir_all(cache_file.parent().unwrap())?;
        fs::write(&cache_file, config_content)?;

        if !alacritty_dir.exists() {
            ctx.log.info(&format!(
                "Creating {} config directory...",
                "alacritty".bold()
            ));
            fs::create_dir_all(&alacritty_dir)?;
        }

        if link_path.exists() || link_path.is_symlink() {
            fs::remove_file(&link_path)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            ctx.log.info(&format!(
                "Linking cache to {} config...",
                "alacritty".bold()
            ));
            symlink(&cache_file, &link_path)
                .with_context(|| format!("Failed to link {:?} -> {:?}", link_path, cache_file))?;
        }

        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let alacritty_dir: PathBuf = self.resolve_config_directory();
        let main_config: PathBuf = alacritty_dir.join("alacritty.toml");
        let theme_path: PathBuf = alacritty_dir.join(self.target_file_name(""));
        let import_line: String = format!("import = [\"{}\"]", theme_path.display());

        if !main_config.exists() {
            return Some(format!(
                "No config found. Create {} and add:\n      {}",
                main_config.display().to_string().cyan(),
                import_line.yellow()
            ));
        }

        let content = fs::read_to_string(&main_config).unwrap_or_default();
        if !content.contains("current_theme.toml") {
            return Some(format!(
                "Add this line to your {}:\n      {}",
                main_config.display().to_string().cyan(),
                import_line.yellow()
            ));
        }

        None
    }
}

impl AlacrittyGenerator {
    /// Build TOML theme for Alacritty
    pub fn build_config(&self, p: &Palette, name: &str) -> String {
        let a = &p.ansi;

        format!(
            r#"# Theme: {name}, generated by Iris

[colors.primary]
background = "{bg}"
foreground = "{fg}"

[colors.cursor]
cursor = "{white}"
text   = "{bg}"

[colors.selection]
background = "{sel}"
text       = "{fg}"

[colors.normal]
black   = "{c0}"
red     = "{c1}"
green   = "{c2}"
yellow  = "{c3}"
blue    = "{c4}"
magenta = "{c5}"
cyan    = "{c6}"
white   = "{c7}"

[colors.bright]
black   = "{c8}"
red     = "{c9}"
green   = "{c10}"
yellow  = "{c11}"
blue    = "{c12}"
magenta = "{c13}"
cyan    = "{c14}"
white   = "{c15}"
"#,
            name = name,
            bg = p.bg,
            fg = p.fg,
            white = p.white,
            sel = p.sel,
            c0 = a[0],
            c1 = a[1],
            c2 = a[2],
            c3 = a[3],
            c4 = a[4],
            c5 = a[5],
            c6 = a[6],
            c7 = a[7],
            c8 = a[8],
            c9 = a[9],
            c10 = a[10],
            c11 = a[11],
            c12 = a[12],
            c13 = a[13],
            c14 = a[14],
            c15 = a[15],
        )
    }
}
