use crate::{
    core::IrisContext,
    models::Palette,
    modules::ConfigGenerator,
    utils::{self, Status},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for Alacritty terminal
pub struct AlacrittyGenerator;

impl ConfigGenerator for AlacrittyGenerator {
    fn name(&self) -> &str {
        "alacritty"
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let task = Status::step(&format!("Configuring {}...", self.name().cyan()), 2);

        let alacritty_dir = dirs::home_dir()
            .context("Cannot get the home directory!")?
            .join(".config/alacritty");

        let cache_file: PathBuf = ctx.paths.cache.join("alacritty_theme.toml");
        let link_path: PathBuf = alacritty_dir.join("current_theme.toml");

        let config_content: String =
            self.build_config(p, &utils::capitalize(&ctx.state.current_theme));

        fs::create_dir_all(&ctx.paths.cache).context("Failed to create cache directory")?;
        fs::write(&cache_file, config_content)
            .with_context(|| format!("Failed to write alacritty cache to {:?}", cache_file))?;

        task.info(&format!(
            "Theme {} generated in cache.",
            utils::capitalize(&ctx.state.current_theme).yellow()
        ));

        if !alacritty_dir.exists() {
            Status::warn("Alacritty config directory not found. Creating it...", 3);
            std::fs::create_dir_all(&alacritty_dir).ok();
        }

        if link_path.exists() || link_path.is_symlink() {
            std::fs::remove_file(&link_path).ok();
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            task.info("Linking cache to Alacritty config...");
            symlink(&cache_file, &link_path).with_context(|| {
                format!(
                    "Failed to create symlink {:?} -> {:?}",
                    link_path, cache_file
                )
            })?;
        }

        task.done(Some(&format!("{} sync complete.", self.name().cyan())));
        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let alacritty_dir: PathBuf = dirs::home_dir()?.join(".config/alacritty");
        let main_config: PathBuf = alacritty_dir.join("alacritty.toml");

        if main_config.exists() {
            let content: String = fs::read_to_string(&main_config).unwrap_or_default();
            if content.contains("current_theme.toml") {
                return None;
            }

            Some(format!(
                "Theme won't load until you add to {}:\n     {}",
                "alacritty.toml".cyan(),
                "import = [\"~/.config/alacritty/current_theme.toml\"]".yellow()
            ))
        } else {
            Some(format!(
                "No {} found. Create it and add:\n     {}",
                "alacritty.toml".cyan(),
                "import = [\"~/.config/alacritty/current_theme.toml\"]".yellow()
            ))
        }
    }
}

impl AlacrittyGenerator {
    /// Build TOML theme for Alacritty
    pub fn build_config(&self, p: &Palette, name: &str) -> String {
        let a = &p.ansi;

        format!(
            r#"# Theme: {name}, generated by Iris

[colors.primary]
background = "{bg}"
foreground = "{fg}"

[colors.cursor]
cursor = "{white}"
text   = "{bg}"

[colors.selection]
background = "{sel}"
text       = "{fg}"

[colors.normal]
black   = "{c0}"
red     = "{c1}"
green   = "{c2}"
yellow  = "{c3}"
blue    = "{c4}"
magenta = "{c5}"
cyan    = "{c6}"
white   = "{c7}"

[colors.bright]
black   = "{c8}"
red     = "{c9}"
green   = "{c10}"
yellow  = "{c11}"
blue    = "{c12}"
magenta = "{c13}"
cyan    = "{c14}"
white   = "{c15}"
"#,
            name = name,
            bg = p.bg,
            fg = p.fg,
            white = p.white,
            sel = p.sel,
            c0 = a[0],
            c1 = a[1],
            c2 = a[2],
            c3 = a[3],
            c4 = a[4],
            c5 = a[5],
            c6 = a[6],
            c7 = a[7],
            c8 = a[8],
            c9 = a[9],
            c10 = a[10],
            c11 = a[11],
            c12 = a[12],
            c13 = a[13],
            c14 = a[14],
            c15 = a[15],
        )
    }
}
