use crate::{
    core::IrisContext,
    models::Palette,
    modules::{Generator, GeneratorType},
    utils::{self},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for Alacritty terminal
pub struct AlacrittyGenerator;

impl Generator for AlacrittyGenerator {
    fn name(&self) -> &str {
        "alacritty"
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::Terminal
    }

    fn target_file_name(&self, _theme: &str) -> String {
        "current_theme.toml".into()
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let alacritty_dir: PathBuf = self.resolve_config_directory();
        let theme_file_name: String = self.target_file_name("");
        let cache_file: PathBuf = ctx.paths.cache.join("alacritty").join(&theme_file_name);
        let link_path: PathBuf = alacritty_dir.join(&theme_file_name);

        let config_content: String = self.build_config(p);
        if let Some(parent) = cache_file.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create cache directory for {}", self.name()))?;
        }

        fs::write(&cache_file, config_content)
            .with_context(|| format!("Failed to write alacritty cache to {:?}", cache_file))?;

        if !alacritty_dir.exists() {
            ctx.log.info(&format!(
                "Creating {} config directory...",
                "alacritty".bold()
            ));
            fs::create_dir_all(&alacritty_dir)?;
        }

        if link_path.exists() || link_path.is_symlink() {
            fs::remove_file(&link_path)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            ctx.log.info(&format!(
                "Linking cache to {} config...",
                "alacritty".bold()
            ));
            symlink(&cache_file, &link_path)
                .with_context(|| format!("Failed to link {:?} -> {:?}", link_path, cache_file))?;
        }

        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let alacritty_dir: PathBuf = self.resolve_config_directory();
        let main_config: PathBuf = alacritty_dir.join("alacritty.toml");
        let theme_path: PathBuf = alacritty_dir.join(self.target_file_name(""));
        let import_line: String = format!("import = [\"{}\"]", theme_path.display());

        if !main_config.exists() {
            return Some(format!(
                "No config found. Create {} and add:\n      {}",
                main_config.display().to_string().cyan(),
                import_line.yellow()
            ));
        }

        let content = fs::read_to_string(&main_config).unwrap_or_default();
        if !content.contains("current_theme.toml") {
            return Some(format!(
                "Add this line to your {}:\n      {}",
                main_config.display().to_string().cyan(),
                import_line.yellow()
            ));
        }

        None
    }
}

impl AlacrittyGenerator {
    /// Build TOML theme for Alacritty
    pub fn build_config(&self, p: &Palette) -> String {
        let a = &p.ansi;

        format!(
            r#"# Theme: {name}, generated by Iris

[colors.primary]
background = "{bg}"
foreground = "{fg}"

[colors.cursor]
cursor = "{white}"
text   = "{bg}"

[colors.selection]
background = "{sel}"
text       = "{fg}"

[colors.normal]
black   = "{c0}"
red     = "{c1}"
green   = "{c2}"
yellow  = "{c3}"
blue    = "{c4}"
magenta = "{c5}"
cyan    = "{c6}"
white   = "{c7}"

[colors.bright]
black   = "{c8}"
red     = "{c9}"
green   = "{c10}"
yellow  = "{c11}"
blue    = "{c12}"
magenta = "{c13}"
cyan    = "{c14}"
white   = "{c15}"
"#,
            name = utils::capitalize(&p.name),
            bg = p.bg,
            fg = p.fg,
            white = p.white,
            sel = p.sel,
            c0 = a[0],
            c1 = a[1],
            c2 = a[2],
            c3 = a[3],
            c4 = a[4],
            c5 = a[5],
            c6 = a[6],
            c7 = a[7],
            c8 = a[8],
            c9 = a[9],
            c10 = a[10],
            c11 = a[11],
            c12 = a[12],
            c13 = a[13],
            c14 = a[14],
            c15 = a[15],
        )
    }
}

/// Unit-tests for alacritty
#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::create_test_context;
    use tempdir::TempDir;

    #[test]
    fn should_return_alacritty_metadata() {
        let generator = AlacrittyGenerator;
        assert_eq!(generator.name(), "alacritty");
        assert_eq!(generator.generator_type(), GeneratorType::Terminal);
        assert_eq!(generator.target_file_name("nord"), "current_theme.toml");
    }

    #[test]
    fn should_build_correct_alacritty_toml() {
        let generator = AlacrittyGenerator;
        let p = Palette::mock();
        let config = generator.build_config(&p);

        assert!(config.contains(&format!("background = \"{}\"", p.bg)));
        assert!(config.contains(&format!("foreground = \"{}\"", p.fg)));
        assert!(config.contains("[colors.normal]"));
        assert!(config.contains("[colors.bright]"));
        assert!(config.contains(&format!("black   = \"{}\"", p.ansi[0])));
        assert!(config.contains(&format!("white   = \"{}\"", p.ansi[15])));
    }

    #[test]
    fn should_generate_setup_hint_for_alacritty() {
        let generator = AlacrittyGenerator;
        let temp_dir: TempDir = TempDir::new("alacritty_test").unwrap();

        temp_env::with_vars(
            vec![
                ("XDG_CONFIG_HOME", Some(temp_dir.path())),
                ("HOME", Some(temp_dir.path())),
            ],
            || {
                let alacritty_dir = generator.resolve_config_directory();
                let main_config = alacritty_dir.join("alacritty.toml");

                let hint_no_config = generator.setup_hint();
                assert!(hint_no_config.is_some());
                assert!(hint_no_config.unwrap().contains("No config found"));

                fs::create_dir_all(&alacritty_dir).unwrap();
                fs::write(&main_config, "[window]\nopacity = 0.9").unwrap();
                let hint_no_import = generator.setup_hint();
                assert!(hint_no_import.is_some());
                assert!(hint_no_import.unwrap().contains("import = ["));

                fs::write(&main_config, "import = [\"current_theme.toml\"]").unwrap();
                assert!(generator.setup_hint().is_none());
            },
        );
    }

    #[test]
    fn should_apply_theme_for_alacritty() {
        if which::which("alacritty").is_err() {
            return;
        }

        let (tmp_dir, ctx) = create_test_context();
        let generator = AlacrittyGenerator;
        let p = Palette::mock();

        temp_env::with_vars(
            vec![
                ("XDG_CONFIG_HOME", Some(tmp_dir.path())),
                ("HOME", Some(tmp_dir.path())),
            ],
            || {
                let result = generator.apply(&p, &ctx);
                assert!(result.is_ok());

                let cache_file = ctx.paths.cache.join("alacritty").join("current_theme.toml");
                assert!(cache_file.exists(), "Theme missing in Iris cache");

                let alacritty_dir = generator.resolve_config_directory();
                let link_path = alacritty_dir.join("current_theme.toml");
                assert!(
                    link_path.exists(),
                    "Symlink missing in Alacritty config dir"
                );

                #[cfg(unix)]
                {
                    let meta = fs::symlink_metadata(&link_path).expect("Failed to get metadata");
                    assert!(meta.file_type().is_symlink(), "Target is not a symlink");
                }
            },
        );
    }
}
