use crate::{
    core::IrisContext,
    models::Palette,
    modules::Generator,
    utils::{self},
};
use anyhow::{Context, Result};
use colored::Colorize;
use std::{fs, path::PathBuf};

/// Config generator for ghostty terminal
pub struct GhosttyGenerator;

impl Generator for GhosttyGenerator {
    fn name(&self) -> &str {
        "ghostty"
    }

    fn target_file_name(&self, _theme: &str) -> String {
        "current_theme.conf".into()
    }

    fn apply(&self, p: &Palette, ctx: &IrisContext) -> Result<()> {
        let ghostty_dir: PathBuf = self.resolve_config_directory();
        let theme_file_name: String = self.target_file_name(&ctx.state.current_theme);
        let cache_file: PathBuf = ctx.paths.cache.join("ghostty").join(&theme_file_name);
        let link_path: PathBuf = ghostty_dir.join(&theme_file_name);

        let config_content: String =
            self.build_config(p, &utils::capitalize(&ctx.state.current_theme));

        if let Some(parent) = cache_file.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create cache directory for {}", self.name()))?;
        }

        fs::write(&cache_file, config_content)
            .with_context(|| format!("Failed to write ghostty cache to {:?}", cache_file))?;

        if !ghostty_dir.exists() {
            ctx.log.info(&format!(
                "Creating {} config directory...",
                "ghostty".bold()
            ));
            fs::create_dir_all(&ghostty_dir)?;
        }

        if link_path.exists() || link_path.is_symlink() {
            fs::remove_file(&link_path)?;
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            ctx.log
                .info(&format!("Linking cache to {} config...", "ghostty".bold()));
            symlink(&cache_file, &link_path)
                .with_context(|| format!("Failed to link {:?} -> {:?}", link_path, cache_file))?;
        }

        Ok(())
    }

    fn setup_hint(&self) -> Option<String> {
        let ghostty_dir: PathBuf = self.resolve_config_directory();
        let config_path: PathBuf = ghostty_dir.join("config");
        let import_line: String = format!("config-file = {}", self.target_file_name(""));

        if !config_path.exists() {
            return Some(format!(
                "No config found. Create {} and add:\n      {}",
                config_path.display().to_string().cyan(),
                import_line.yellow()
            ));
        }

        let content: String = fs::read_to_string(&config_path).unwrap_or_default();
        if !content.contains(&import_line) {
            return Some(format!(
                "Theme won't load until you add to {}:\n      {}",
                config_path.display().to_string().cyan(),
                import_line.yellow()
            ));
        }

        None
    }
}

impl GhosttyGenerator {
    /// Build config theme for ghostty
    pub fn build_config(&self, p: &Palette, name: &str) -> String {
        let mut cfg = String::new();
        cfg.push_str(&format!("# Theme: {}, generated by Iris\n\n", name));

        cfg.push_str(&format!("background = {}\n", p.bg));
        cfg.push_str(&format!("foreground = {}\n", p.fg));
        cfg.push_str(&format!("cursor-color = {}\n", p.white));
        cfg.push_str(&format!("selection-background = {}\n", p.sel));
        cfg.push_str(&format!("selection-foreground = {}\n\n", p.bg));

        for (idx, color) in p.ansi.iter().enumerate() {
            cfg.push_str(&format!("palette = {}={}\n", idx, color));
        }

        cfg
    }
}
